from .candidateLocationReview import CandidateLocationReview
from .candidateExperienceReview import CandidateExperienceReview
from .candidateSkillReview import CandidateSkillReview
from .candidateInstantFeedbackProcessor import CandidateInstantFeedbackProcessor